apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.9.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: memcached-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: test
  displayName: memcached
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: []
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - asdfdsa
  links:
  - name: Memcached Operator
    url: https://memcached-operator.domain
  maintainers:
  - email: adsfd
    name: asdf
  maturity: alpha
  provider:
    name: asdfasd
    url: asdfadsf
  version: 0.0.1
