apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: memcached-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Memcached is the Schema for the memcacheds API
      displayName: Memcached
      kind: Memcached
      name: memcacheds.cache.example.com
      specDescriptors:
      - description: Foo is an example field of Memcached. Edit memcached_types.go
          to remove/update
        displayName: Size
        path: size
      - displayName: Val Test
        path: valTest
      - displayName: Val
        path: val
      statusDescriptors:
      - displayName: Nodes Test
        path: nodesTest
      - description: 'INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
          Important: Run "make" to regenerate code after modifying this file'
        displayName: Nodes
        path: nodes
      version: v1alpha1
  description: test
  displayName: memcached
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - asdfdsa
  links:
  - name: Memcached Operator
    url: https://memcached-operator.domain
  maintainers:
  - email: adsfd
    name: asdf
  maturity: alpha
  provider:
    name: asdfasd
    url: asdfadsf
  version: 0.0.0
